[profile.default]
solc_version = "0.8.28"
src = "contracts/src"
out = "contracts/out"
libs = ["contracts/lib"]
script = 'contracts/scripts'
broadcast = 'contracts/broadcast'
cache_path = 'contracts/cache'
test = 'contracts/test'
optimizer = true
optimizer_runs = 200
via_ir = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


ignore = ["contracts/lib/signature-validator/contracts/EIP6492.sol"]

remappings = [
    '@openzeppelin/=contracts/lib/openzeppelin-contracts/',
    'forge-std/=contracts/lib/forge-std/src/'
]